version: '3.4'

services:
  computerpartsshopweb:
    image: ${DOCKER_REGISTRY-}computerpartsshopweb
    build:
      context: .
      dockerfile: src/Frontend/eCommerce.ComputerParts.Shop.Web/Dockerfile
    depends_on:
      - "sqlserver"
  computerpartsshopservice:
    image: ${DOCKER_REGISTRY-}computerpartsshopservice
    build:
      context: .
      dockerfile: src/Backend/eCommerce.ComputerParts.Shop.Service/Dockerfile
    depends_on:
      - "sqlserver"
  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge
    ports:
      - "1433:1433"
    environment:
      - SA_PASSWORD=@someThingComplicated1234
      - ACCEPT_EULA=Y

